# Part 1

In [1]:
revenues = [120, 250, 80, 310, 95]
tax_rate = 0.18
discount_rate = 0.10

In [3]:
# 1. Compute revenues including tax
taxed_revenues = [value *(1+ tax_rate) for value in revenues]
taxed_revenues

[141.6, 295.0, 94.39999999999999, 365.79999999999995, 112.1]

In [4]:
taxed_revenues = [r *(1+ tax_rate) for r in revenues]
taxed_revenues

[141.6, 295.0, 94.39999999999999, 365.79999999999995, 112.1]

In [5]:
# 2. Compute final revenues after tax and discount.
final_revenues = [r* (1+ tax_rate) * (1-discount_rate) for r in revenues]
final_revenues

[127.44, 265.5, 84.96, 329.21999999999997, 100.89]

In [6]:
# 3. Create a Boolean list indicating whether revenue > 100.
high_revenues = [r > 100 for r in revenues]
high_revenues

[True, True, False, True, False]

In [7]:
# 4. Create a Boolean list indicating whether revenue > 100.
middle_revenues = [r < 100 and r > 300 for r in revenues]
middle_revenues

[False, False, False, False, False]

5. Add Markdown explanation: Why do parentheses matter in the formula?

calculation start from formulas inside parentheses.ANd then the results calculate with outside formulas  

# Part 2

In [8]:
sales = [120, 250, 80, 310, 95]

In [10]:
# Compute total revenue manually using a loop.
total_revenue = 0
for value in sales:
    total_revenue = total_revenue + value
total_revenue

855

In [11]:
# Compute average revenue.
average_revenue = total_revenue / len(sales)
average_revenue

171.0

In [12]:
# Identify the maximum value without using max().
max_value = 0
for value in sales:
    if value > max_value:
        max_value = value
max_value

310

In [13]:
# Count how many values are greater than 150.
grater_than_150 = 0
for value in sales:
    if value >150:
        grater_than_150 = grater_than_150 + 1
grater_than_150

2

In [14]:
# Create a new list of revenues after adding 5% commission.
revenues_with_commission = [r *1.05 for r in sales]
revenues_with_commission

[126.0, 262.5, 84.0, 325.5, 99.75]

# Part 3

Segmentation rules:

- “Premium” if revenue > 250
- “Standard” if 100 < revenue ≤ 250
- “Low” otherwise

In [24]:
# Create a list of segment labels.
segments = ["premium" if r > 250 else "standard" if r > 100 and r <= 250 else "low" for r in revenues]
segments


['standard', 'standard', 'low', 'premium', 'low']

In [22]:
# Count how many customers fall into each segment.
count_customers = [0, 0, 0]
for segment in segments:
    if segment == "premium":
        count_customers[0] = count_customers[0] + 1
    elif segment == "standard":
        count_customers[1] = count_customers[1] + 1
    else:
        count_customers[2] = count_customers[2] + 1
count_customers 

[1, 2, 2]

Add Markdown explanation: Why does the order of elif statements matter?

Python evaluates conditional statements from top to bottom. Once it finds a condition that is True, it executes that block and skips the rest of the chain.

If we had put the "Standard" check (r > 100) before the "Premium" check (r > 250), a revenue of 310 would trigger the r > 100 condition and be labeled "Standard." Python would never even look at the "Premium" rule. To get accurate results, you must generally order your conditions from the most specific (or highest value) to the most general (or lowest value).

# part 4

In [25]:
customer_ids = [1, 2, 3, 3, 4, 5, 5, 6]

In [27]:
# Remove duplicates using a set.
customer_ids_set = set(customer_ids)
customer_ids_set


{1, 2, 3, 4, 5, 6}

In [28]:
# Convert back to a list.
customer_ids_list = list(customer_ids_set)
customer_ids_list

[1, 2, 3, 4, 5, 6]

In [29]:
# Compare lengths before and after deduplication.
len(customer_ids), len(customer_ids_list)

(8, 6)

Explain in Markdown why sets are unordered.


Sets are unordered because they are implemented using a data structure called a Hash Table.Unlike a List, which stores items in a specific sequence (like passengers in a row of seats), a Set uses a "hashing function" to assign each element a unique "address" in memory. This allows the computer to find an item almost instantly because it knows the exact address, rather than searching through the whole list. Because the goal is speed and uniqueness rather than sequence, the order in which items appear is not preserved.

# Part 5

In [31]:
customer = {
    "name": "Anna",
    "revenue": 250,
    "city": "Yerevan"
}

In [36]:
# Add a new key "segment" based on revenue.
segment= ["premium" if customer["revenue"] > 250 else "standard"]
segment


['standard']

In [37]:
# Update revenue to 300.
customer ["revenue"] = 300
customer ["revenue"]

300

In [38]:
# Remove "city"
del customer ["city"]
customer

{'name': 'Anna', 'revenue': 300}

In [40]:
# Loop over the dictionary and print key-value pairs.
for key, value in customer.items():
    print(key, ":", value)

name : Anna
revenue : 300


Add Markdown explanation: Why are dictionaries useful for structured data?

Dictionaries are essential for structured data because they use key-value pairs, which allow us to label our data. Unlike a list where you have to remember that "index 0 is the name" and "index 1 is the revenue," a dictionary explicitly links a label (the key) to its data (the value).

This makes the data:

Self-describing: It's immediately clear what each piece of information represents.

Efficient: You can look up a specific value instantly using its key without searching through a whole list.

Flexible: You can easily add or remove fields (keys) for one record without breaking the structure of others.

# part 6

In [1]:
revenues = [120, 250, 80, 310, 95]


In [4]:
#Create a list of revenues after 10% tax.
taxed_revenues = [r * 0.9 for r in revenues]
taxed_revenues

[108.0, 225.0, 72.0, 279.0, 85.5]

In [5]:
#Create a list of revenues greater than 100
high_revenues = [r > 100 for r in revenues ]
high_revenues

[True, True, False, True, False]

In [6]:
#Create a list labeling each revenue as:
#“High” if > 200
#“Normal” otherwise
labels = ["High" if r > 200 else "Normal" for r in revenues]
labels


['Normal', 'High', 'Normal', 'High', 'Normal']

Compare list comprehension vs loop in Markdown:
In a Markdown cell in your Jupyter Notebook, you should explain the trade-offs between the two methods.

Key points to include in your explanation:

Conciseness: List comprehensions allow you to perform iteration, filtering, and transformation in a single line of code.

Readability: For simple operations, comprehensions are often easier to read as they follow a "natural language" flow.

Performance: List comprehensions are generally faster than traditional for loops because they are optimized internally by Python.

Complexity: Traditional loops are better for complex logic with multiple nested steps, while comprehensions are best for straightforward transformations.

# Part 7

In [7]:
import pandas as pd

data = {
    "revenue": revenues
}

df = pd.DataFrame(data)
df

,revenue
0,120
1,250
2,80
3,310
4,95


In [8]:
# 1. Add column "revenue_after_tax" (Vectorized math!)
df["revenue_after_tax"] = df["revenue"] * 0.9

In [9]:
# 2. Add column "segment" using conditional logic
# This is the Pandas version of your if-else logic
df["segment"] = df["revenue"].apply(lambda x: "High" if x > 200 else "Normal")

In [10]:
# 3. Filter rows where revenue > 100
df = df[df["revenue"] > 100]

In [11]:
# 4. Remove the "revenue_after_tax" column
df = df.drop(columns=["revenue_after_tax"])

In [12]:
# 5. Print the shape of the DataFrame
print(f"DataFrame Shape: {df.shape}")
print(df)

DataFrame Shape: (3, 2)
   revenue segment
0      120  Normal
1      250    High
3      310    High


Why is this easier than manual loops? (Markdown)

Conciseness: Operations that take 4-5 lines in a manual loop (like multiplying every item by tax) can be done in one line with Pandas using vectorized operations.

Performance: Pandas is built on top of C and NumPy. It performs math on entire blocks of memory at once, making it significantly faster than Python's standard for loops when dealing with large datasets.

Readability: The code describes what you want to do (e.g., df.drop()) rather than how to do it (e.g., "Loop through the list, find the index, remove the item").

Integrated Tools: Features like .shape, .info(), and .describe() provide instant summaries of your data that would require manual code to calculate otherwise.

# mutable and immutable objects

Mutable: Objects that can be changed after they are created (e.g., Lists and Dictionaries). You can add, remove, or swap items in place.

Immutable: Objects that cannot be changed once created (e.g., Tuples, Strings, and Integers). Any "change" actually creates a brand-new object in memory.

# loops VS vectorization

Loops: Python must look at each row one by one, interpret the code, and check types every single time. This is "overhead" that slows things down.

Vectorization: Pandas (via NumPy) performs operations in C, which allows it to process entire blocks of data simultaneously across your computer's memory.

# Boolean logic VS SQL WHERE

In Python, Boolean logic (e.g., value > 120) acts as a filter to decide which items stay and which are dropped.

This is conceptually identical to a SQL WHERE clause, which filters a database table to return only rows that meet specific logical criteria.

# lists VS DataFrames

A DataFrame is essentially a collection of Series (columns) aligned by a common index.

Since a Series is basically a "smarter" version of a List, understanding how to iterate, index, and transform lists is the foundational skill needed to manipulate complex tabular data.